@echo off
TITLE FRIDAY - Launch Website Project in VS Code (Windows 10)
COLOR 0B

echo ================================================================
echo    FRIDAY AI - VS CODE WEBSITE STUDIO LAUNCHER (WINDOWS 10)
echo    Operator: Boss Chris
echo ================================================================
echo.

:: Check if VS Code is installed and in PATH
where code >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [!] 'code' command not found in your system PATH.
    echo     Checking standard VS Code installation paths...
    if exist "%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe" (
        set "VSCODE_PATH=%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe"
    ) else if exist "%ProgramFiles%\Microsoft VS Code\Code.exe" (
        set "VSCODE_PATH=%ProgramFiles%\Microsoft VS Code\Code.exe"
    ) else if exist "%ProgramFiles(x86)%\Microsoft VS Code\Code.exe" (
        set "VSCODE_PATH=%ProgramFiles(x86)%\Microsoft VS Code\Code.exe"
    ) else (
        echo [X] Visual Studio Code does not appear to be installed.
        echo     Download it for free from: https://code.visualstudio.com/
        echo.
        pause
        exit /b 1
    )
) else (
    set "VSCODE_PATH=code"
)

:: Create website workspace folder
set "TARGET_DIR=%USERPROFILE%\Desktop\Chris_Website_Project"
if not exist "%TARGET_DIR%" (
    mkdir "%TARGET_DIR%"
)

:: Create sample modern index.html if it doesn't exist
if not exist "%TARGET_DIR%\index.html" (
    echo [i] Generating starter website for Boss Chris...
    (
        echo ^<!DOCTYPE html^>
        echo ^<html lang="en"^>
        echo ^<head^>
        echo   ^<meta charset="UTF-8"^>
        echo   ^<meta name="viewport" content="width=device-width, initial-scale=1.0"^>
        echo   ^<title^>Chris - Modern Web Studio^</title^>
        echo   ^<script src="https://cdn.tailwindcss.com"^>^</script^>
        echo ^</head^>
        echo ^<body class="bg-slate-950 text-slate-100 min-h-screen flex flex-col items-center justify-center p-6"^>
        echo   ^<div class="max-w-2xl w-full p-8 rounded-2xl bg-slate-900 border border-cyan-500/40 shadow-2xl text-center space-y-6"^>
        echo     ^<h1 class="text-4xl font-extrabold text-cyan-400"^>Boss Chris Web Studio^</h1^>
        echo     ^<p class="text-slate-300"^>Designed by FRIDAY AI for Windows 10 ^&amp; Visual Studio Code.^</p^>
        echo     ^<button onclick="alert('Welcome, Boss Chris!')" class="px-6 py-3 rounded-xl bg-cyan-400 text-slate-950 font-bold hover:bg-cyan-300 transition-all"^>Explore Showcase^</button^>
        echo   ^</div^>
        echo ^</body^>
        echo ^</html^>
    ) > "%TARGET_DIR%\index.html"
)

:: Create README.md
(
    echo # Chris's Web Project - Generated by FRIDAY AI
    echo.
    echo Operator: Boss Chris
    echo Environment: Windows 10
    echo.
    echo ## Quick Start
    echo 1. Install Live Server extension in VS Code: `ritwickdey.LiveServer`
    echo 2. Click "Go Live" at the bottom right of VS Code to launch the live preview!
) > "%TARGET_DIR%\README.md"

echo [*] Opening project folder in VS Code...
echo     Path: %TARGET_DIR%
echo.

if "%VSCODE_PATH%"=="code" (
    code "%TARGET_DIR%"
) else (
    start "" "%VSCODE_PATH%" "%TARGET_DIR%"
)

echo [OK] Visual Studio Code launched successfully for Boss Chris!
timeout /t 3 >nul
