import React, { useState } from 'react';
import { X, FileText, Table, FileCode, Download, Sparkles, Check } from 'lucide-react';

interface DocumentGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onGenerateDocument: (docType: string, title: string, prompt: string) => void;
}

export const DocumentGeneratorModal: React.FC<DocumentGeneratorModalProps> = ({
  isOpen,
  onClose,
  onGenerateDocument
}) => {
  const [docType, setDocType] = useState<'word' | 'excel' | 'script' | 'markdown'>('word');
  const [title, setTitle] = useState('Executive_System_Report');
  const [description, setDescription] = useState('Hardware metrics, system security audit, and maintenance action items.');
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  if (!isOpen) return null;

  const handleCreate = () => {
    onGenerateDocument(docType, title, description);
    onClose();
  };

  const handleDirectDownload = () => {
    let filename = `${title}.${docType === 'word' ? 'docx' : docType === 'excel' ? 'csv' : docType === 'script' ? 'ps1' : 'md'}`;
    let content = '';

    if (docType === 'word') {
      content = `# F.R.I.D.A.Y. Executive Report\n\nTitle: ${title}\nDate: ${new Date().toLocaleDateString()}\nSystem Status: ALL NOMINAL\n\n## Overview\n${description}\n\n## Hardware Telemetry\n- CPU Utilization: 24%\n- RAM Allocated: 6.5 GB / 16.0 GB\n- Primary Storage: 36% Used\n\n## Authorization\nGenerated by F.R.I.D.A.Y. Protocol Mark-VI`;
    } else if (docType === 'excel') {
      content = `Timestamp,Metric,Value,Status\n${new Date().toISOString()},CPU_Load,24%,Nominal\n${new Date().toISOString()},RAM_Usage,41%,Nominal\n${new Date().toISOString()},Disk_Space,611_GB,Healthy\n${new Date().toISOString()},Network_Ping,14ms,Fast`;
    } else if (docType === 'script') {
      content = `# F.R.I.D.A.Y. Windows Maintenance Automation Script\nWrite-Host "[F.R.I.D.A.Y.] Initiating Routine System Diagnosis..." -ForegroundColor Cyan\nGet-Process | Sort-Object CPU -Descending | Select-Object -First 5 ProcessName, CPU, WorkingSet64\nClear-RecycleBin -Force -ErrorAction SilentlyContinue\nWrite-Host "[F.R.I.D.A.Y.] Telemetry check complete." -ForegroundColor Green`;
    } else {
      content = `# ${title}\n\n*Created by F.R.I.D.A.Y. AI Controller*\n\n${description}\n\n### System Actions\n1. Initialized diagnostic daemon\n2. Monitored hardware thresholds\n3. Exported structured report`;
    }

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="relative w-full max-w-xl bg-[#030818] border border-cyan-500/50 rounded-2xl shadow-[0_0_50px_rgba(0,255,255,0.25)] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5 bg-slate-900/90 border-b border-cyan-500/30">
          <div className="flex items-center space-x-2.5">
            <FileText className="w-5 h-5 text-cyan-400" />
            <div>
              <h2 className="font-chakra text-sm font-bold text-white tracking-wider">
                DOCUMENT & SCRIPT CREATION ENGINE
              </h2>
              <p className="font-mono-hud text-[11px] text-cyan-400/80">
                Generate Word (.docx), Excel (.csv), or PowerShell (.ps1) files
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-5 space-y-4 font-chakra text-xs">
          {/* Format Selector */}
          <div>
            <label className="block text-slate-300 font-bold mb-2">SELECT DOCUMENT FORMAT</label>
            <div className="grid grid-cols-4 gap-2">
              <button
                type="button"
                onClick={() => setDocType('word')}
                className={`p-3 rounded-xl border flex flex-col items-center justify-center space-y-1.5 transition-all ${
                  docType === 'word'
                    ? 'bg-cyan-950 border-cyan-400 text-cyan-200 shadow-[0_0_12px_rgba(0,255,255,0.3)]'
                    : 'bg-slate-950/80 border-cyan-950 text-slate-400 hover:border-cyan-500/40'
                }`}
              >
                <FileText className="w-5 h-5 text-cyan-400" />
                <span className="font-bold">Word (.docx)</span>
              </button>

              <button
                type="button"
                onClick={() => setDocType('excel')}
                className={`p-3 rounded-xl border flex flex-col items-center justify-center space-y-1.5 transition-all ${
                  docType === 'excel'
                    ? 'bg-cyan-950 border-cyan-400 text-cyan-200 shadow-[0_0_12px_rgba(0,255,255,0.3)]'
                    : 'bg-slate-950/80 border-cyan-950 text-slate-400 hover:border-cyan-500/40'
                }`}
              >
                <Table className="w-5 h-5 text-emerald-400" />
                <span className="font-bold">Excel (.csv)</span>
              </button>

              <button
                type="button"
                onClick={() => setDocType('script')}
                className={`p-3 rounded-xl border flex flex-col items-center justify-center space-y-1.5 transition-all ${
                  docType === 'script'
                    ? 'bg-cyan-950 border-cyan-400 text-cyan-200 shadow-[0_0_12px_rgba(0,255,255,0.3)]'
                    : 'bg-slate-950/80 border-cyan-950 text-slate-400 hover:border-cyan-500/40'
                }`}
              >
                <FileCode className="w-5 h-5 text-amber-400" />
                <span className="font-bold">PowerShell (.ps1)</span>
              </button>

              <button
                type="button"
                onClick={() => setDocType('markdown')}
                className={`p-3 rounded-xl border flex flex-col items-center justify-center space-y-1.5 transition-all ${
                  docType === 'markdown'
                    ? 'bg-cyan-950 border-cyan-400 text-cyan-200 shadow-[0_0_12px_rgba(0,255,255,0.3)]'
                    : 'bg-slate-950/80 border-cyan-950 text-slate-400 hover:border-cyan-500/40'
                }`}
              >
                <Sparkles className="w-5 h-5 text-sky-400" />
                <span className="font-bold">Markdown (.md)</span>
              </button>
            </div>
          </div>

          {/* Document Title */}
          <div>
            <label className="block text-slate-300 font-bold mb-1">DOCUMENT TITLE</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full bg-slate-950 border border-cyan-500/30 rounded-lg px-3 py-2 text-cyan-100 font-mono-hud text-xs focus:outline-none focus:border-cyan-400"
            />
          </div>

          {/* Prompt / Brief */}
          <div>
            <label className="block text-slate-300 font-bold mb-1">CONTENT SPECIFICATIONS</label>
            <textarea
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full bg-slate-950 border border-cyan-500/30 rounded-lg px-3 py-2 text-cyan-100 font-mono-hud text-xs focus:outline-none focus:border-cyan-400"
              placeholder="Provide instructions or data topics for F.R.I.D.A.Y. to draft..."
            />
          </div>

          {/* Action Buttons */}
          <div className="flex items-center justify-between pt-2 border-t border-cyan-500/20">
            <button
              onClick={handleDirectDownload}
              className="px-4 py-2 rounded-lg bg-slate-900 hover:bg-slate-800 border border-cyan-500/40 text-cyan-300 font-bold flex items-center space-x-1.5 transition-colors"
            >
              {downloadSuccess ? <Check className="w-4 h-4 text-emerald-400" /> : <Download className="w-4 h-4" />}
              <span>{downloadSuccess ? 'DOWNLOADED' : 'INSTANT DOWNLOAD'}</span>
            </button>

            <button
              onClick={handleCreate}
              className="px-5 py-2 rounded-lg bg-gradient-to-r from-cyan-600 to-sky-500 hover:from-cyan-500 hover:to-sky-400 text-slate-950 font-bold flex items-center space-x-1.5 shadow-[0_0_15px_rgba(0,255,255,0.4)] transition-all"
            >
              <Sparkles className="w-4 h-4" />
              <span>DISPATCH TO F.R.I.D.A.Y. CONSOLE</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
